labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Models/CharacterModel.cs
/*
 * Daniel Brenes
 * Lab 5 ITSE 1430
 * Character Creator
 * Character Class
 * 12/11/2020
 */
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CharacterCreator.Web.Models
{

    public class CharacterModel// : IValidatableObject
    {
        public CharacterModel ()
        { }

        public CharacterModel ( Character character )
        {
            Id = character.Id;
            Name = character.Name;
            Description = character.Description;
            Profession = character.Profession;
            Race = character.Race;
            Strength = character.Strength;
            Intelligence = character.Intelligence;
            Agility = character.Agility;
            Constitution = character.Constitution;
            Charisma = character.Charisma;

        }

        public Character ToCharacter ()
        {
            return new Character() {
                Id = Id,
                Name = Name,
                Profession = Profession,
                Race = Race,
                Strength = Strength,
                Agility = Agility,
                Intelligence = Intelligence,
                Constitution = Constitution,
                Charisma = Charisma,
                Description = Description,

            };
        }

        public int Id { get; set; } 

        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }

        [Required(AllowEmptyStrings = false)]
        public string Profession { get; set; }

        [Required(AllowEmptyStrings = false)]
        public string Race { get; set; }

        [Range(0, 100, ErrorMessage = "Strength must be between 0 and 100.")]
        public int Strength { get; set; }

        [Range(0, 100, ErrorMessage = "Intelligence must be between 0 and 100.")]
        public int Intelligence { get; set; }

        [Range(0, 100, ErrorMessage = "Agility must be between 0 and 100.")]
        public int Agility { get; set; }

        [Range(0, 100, ErrorMessage = "Constitution must be between 0 and 100.")]
        public int Constitution { get; set; }

        [Range(0, 100, ErrorMessage = "Charisma must be between 0 and 100.")]
        public int Charisma { get; set; }


        public string Description { get; set; }


        //public IEnumerable<ValidationResult> Validate ( ValidationContext validationContext )
        //{

        //if (String.IsNullOrEmpty(Name))
        //    yield return new ValidationResult("Name of character is required", new[] { nameof(Name) });

        //if (String.IsNullOrEmpty(Profession))
        //    yield return new ValidationResult("Profession is required", new[] { nameof(Profession) });

        //if (String.IsNullOrEmpty(Race))
        //    yield return new ValidationResult("Race is required", new[] { nameof(Race) });

        
        //}
    }
}

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Controllers/CharacterController.cs
/*
 * Daniel Brenes
 * Lab 5 ITSE 1430
 * Character Creator
 * Character Class
 * 12/11/2020
 */
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using CharacterCreator.Web.Models;

namespace CharacterCreator.Web.Controllers
{
    public class CharacterController : Controller
    {
        public CharacterController ()
        {         
                         
        }

        // GET: Character
        public ActionResult Index()
        {
            var characters = s_database.GetAll();

            var model = characters.Select(x => new CharacterModel(x))
                                    .OrderBy(x => x.Name);
            return View("List", model);
        }

        // GET: Edit/{id}
        public ActionResult Details ( int id )
        {
            var character = s_database.Get(id);
            if (character == null)
                return HttpNotFound(); //404

            return View(new CharacterModel(character));
        }

        //GET: Create
        public ActionResult Create () => View(new CharacterModel());

        // POST: Create 
        [HttpPost]
        public ActionResult Create ( CharacterModel model )
        {
            
            if (ModelState.IsValid)
            {
                try
                {
                    var character = s_database.Add(model.ToCharacter());

                    return RedirectToAction(nameof(Details), new { id = character.Id }) ;
                } catch (Exception e)
                {                    
                    ModelState.AddModelError("", e.Message);
                };
            };

            return View(model);
        }

        // GET: Edit/{id}
        public ActionResult Edit ( int id )
        {
            var character = s_database.Get(id);
            if (character == null)
                return HttpNotFound(); //404


            return View(new CharacterModel(character));
        }

        // POST: Edit
        [HttpPost]
        public ActionResult Edit ( CharacterModel model )
        {            
            if (ModelState.IsValid)
            {
                try
                {
                    s_database.Update(model.Id, model.ToCharacter());
                    
                    return RedirectToAction(nameof(Details), new { id = model.Id });
                } catch (Exception e)
                {                    
                    ModelState.AddModelError("", e.Message);
                };
            };

            return View(model);
        }
        // GET: Delete/{id}
        public ActionResult Delete ( int id )
        {
            var character = s_database.Get(id);
            if (character == null)
                return HttpNotFound(); //404


            return View(new CharacterModel(character));
        }

        // POST: Delete
        [HttpPost]
        public ActionResult Delete ( CharacterModel model )
        {            
            try
            {
                s_database.Delete(model.Id);
               
                return RedirectToAction(nameof(Index));
            } catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
            };

            return View(model);
        }

        private readonly static ICharacterDatabase s_database = new CharacterCreator.Memory.MemoryCharacterDatabase();
    }
}

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Controllers/HomeController.cs
/*
 * Daniel Brenes
 * Lab 5 ITSE 1430
 * Character Creator
 * Character Class
 * 12/11/2020
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CharacterCreator.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Character/Create.cshtml
@model CharacterCreator.Web.Models.CharacterModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CharacterModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Race, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Race, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Strength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Strength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Strength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Intelligence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Intelligence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Intelligence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Constitution, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Constitution, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Constitution, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Charisma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charisma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charisma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Character/Delete.cshtml
@model CharacterCreator.Web.Models.CharacterModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this character?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Strength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Strength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Intelligence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Intelligence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Constitution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Constitution)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Charisma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Charisma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Character/Details.cshtml
@model CharacterCreator.Web.Models.CharacterModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CharacterModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Profession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Profession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Race)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Race)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Strength)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Strength)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Intelligence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Intelligence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Agility)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Agility)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Constitution)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Constitution)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Charisma)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Charisma)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Character/Edit.cshtml
@model CharacterCreator.Web.Models.CharacterModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CharacterModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Profession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Race, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Race, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Race, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Strength, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Strength, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Strength, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Intelligence, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Intelligence, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Intelligence, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Agility, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Agility, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Agility, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Constitution, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Constitution, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Constitution, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Charisma, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Charisma, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Charisma, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Character/List.cshtml
@model IEnumerable<CharacterCreator.Web.Models.CharacterModel>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Profession)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Profession)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Race)
        </td>        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Character Creator Web Application.</h2>
<h3>Daniel Brenes</h3>

<address>
    ITSE 1430 Intro to C# Programming<br />
    Fall 2020 - 12.11.2020<br />
    
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:Support@example.com">daniel.brenes@my.tccd.edu</a><br />
    
</address>

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


    <h1>Character Roster</h1>    

labs/Lab 5 - Edit/CharacterCreator.Winforms/CharacterCreator.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Character Roster</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Character Roster", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Characters", "Index", "Character")</li>                    
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Daniel Brenes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>